import type { GlbArticulationSpec } from "./unfold";
import type { ArtworkRenderMode, ArtworkTreatment } from "./embroidery";

/**
 * Core contracts for the product customization engine.
 *
 * The 2D design state is the source of truth. The 3D view is a live preview
 * driven by a CanvasTexture — never the other way around.
 */

export type ImageElement = {
  id: string;
  type: "image";
  /**
   * Durable artwork identity. New project-backed documents always set this.
   * The server verifies that the asset belongs to the same project before a
   * revision is accepted.
   */
  assetId?: string;
  /**
   * Runtime locator used by browser image decoders. It may be an object URL
   * for a legacy/transient design or an authorized project-asset endpoint.
   * It is deliberately not the durable identity and may be omitted from a
   * stored DesignDocument.
   */
  src?: string;
  /** Original asset dimensions, retained for effective-PPI preflight. */
  sourcePixelWidth?: number;
  sourcePixelHeight?: number;
  sourceName?: string;
  sourceMimeType?: string;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  scaleX: number;
  scaleY: number;
  opacity: number;
  /**
   * How this artwork is reproduced on the product. Purely additive: the asset
   * above is never rewritten, so switching back to "print" restores the
   * original pixels exactly. Absent means print.
   */
  treatment?: ArtworkTreatment;
};

export type TextElement = {
  id: string;
  type: "text";
  text: string;
  x: number;
  y: number;
  fontFamily: string;
  fontSize: number;
  fill: string;
  rotation: number;
  scaleX: number;
  scaleY: number;
  opacity: number;
};

export type DesignElement = ImageElement | TextElement;

/** Design for a single printable surface. Order in `elements` is z-order. */
export type SurfaceDesign = {
  elements: DesignElement[];
  /** Optional flat backdrop painted behind all elements. `null` = transparent. */
  background: string | null;
};

export type DesignDocument = {
  productId: string;
  surfaces: Record<string, SurfaceDesign>;
};

/** Optional print-production guides. Purely visual — never exported into artwork. */
export type SurfaceGuides = {
  /** Inset from each edge, in editor pixels. */
  bleed?: number;
  safeArea?: number;
};

/**
 * A named production panel within one continuous print web. The measurements
 * come from the printer's panel-section metadata, not from visual guesswork.
 */
export type EditableSection = {
  id: string;
  label: string;
  /** GLB mesh receiving this part of the shared artwork texture. */
  meshName: string;
  /** Panel bounds inside the print web, in centimetres. */
  xCm: number;
  yCm: number;
  widthCm: number;
  heightCm: number;
  /** Printer-authored orientation for newly placed panel content. */
  contentRotation: number;
  /**
   * Optional print-only transform. This lets the editor keep artwork upright
   * while the horizontal production web receives the quarter-turn required by
   * the physical panel UVs.
   */
  textureRotation?: number;
};

/** One polyline of a dieline overlay, in editor pixels. */
export type DielinePath = { points: number[]; closed: boolean };

/**
 * Data-driven dieline overlay for a surface (cut outlines, crease/fold lines,
 * safety outlines). Generated by the product-onboarding pipeline from the
 * region meshes' true UV boundaries — takes precedence over spec-derived
 * overlays so arbitrary onboarded products get production guides without
 * product-specific code.
 */
export type SurfaceDieline = {
  cuts: DielinePath[];
  creases: DielinePath[];
  safety?: DielinePath[];
};

export type EditableSurface = {
  id: string;
  /** Human label used by the surface selector. */
  label: string;
  /** Optional generated dieline overlay (see SurfaceDieline). */
  dieline?: SurfaceDieline;
  /** Must match a mesh name inside the GLB. Never an index. */
  meshName: string;
  /**
   * Additional GLB meshes driven by the same artwork canvas. Flexible
   * packaging commonly splits one production web across front, gusset and
   * back meshes while retaining a single printable surface.
   */
  meshNames?: string[];
  /** Optional front/gusset/back sections inside the shared production web. */
  sections?: EditableSection[];
  editorWidth: number;
  editorHeight: number;
  /** Real-world print size, shown on the editor's dimension rules. */
  physicalWidthCm: number;
  physicalHeightCm: number;
  /** Display unit for the editor rulers. Measurements remain stored in cm. */
  displayUnit?: "cm" | "in";
  guides?: SurfaceGuides;
  /**
   * Reproduction methods this surface offers. Packaging is printed; a garment
   * panel can also be embroidered. Absent means print only, so no existing
   * product gains a control it cannot honour.
   */
  renderModes?: ArtworkRenderMode[];
  /**
   * Colour of the unprinted substrate. Pouch film and board are white, not
   * transparent — without this the empty canvas' zero alpha renders as black.
   */
  defaultBackground?: string;
};

export type CameraPreset = {
  id: string;
  label: string;
  position: [number, number, number];
  target: [number, number, number];
};

/**
 * How the 3D geometry is produced.
 *  - "glb"            a prepared mesh file (bottles, jars, anything revolved)
 *  - "folded-carton"  generated at runtime from a dieline spec, so the same
 *                     data drives the mesh, the editor canvas and the fold
 *                     animation. Adding a box needs a spec, not a model.
 */
export type ProductFamily = "glb" | "folded-carton" | "pouch";

export type ProductConfig = {
  id: string;
  /** Immutable version that produced this resolved engine configuration. */
  productVersionId?: string;
  /** Deterministic identity for the validated option selection. */
  configurationId?: string;
  /** Validated customer-facing values used to resolve this configuration. */
  optionSelection?: Record<string, string | number | boolean>;
  name: string;
  family: ProductFamily;
  /** Required for family "glb". */
  modelUrl: string;
  /** Required for family "folded-carton" — key into the carton registry. */
  cartonSpecId?: string;
  /** Required for family "pouch" — key into the pouch registry. */
  pouchSpecId?: string;
  /**
   * @deprecated Presentation is derived from the product's construction by
   * `resolveProductPresentation`. Kept so existing configs keep type-checking.
   */
  canOpen?: boolean;
  /**
   * Force a product to render with no structural control even though its
   * construction supports one. Omit for the derived capability.
   */
  presentation?: "static";
  /**
   * Optional authored articulation for a prepared GLB (hinged cases, folding
   * displays). Declared as a contract; see `GlbArticulationSpec`. A product
   * that sets this reports `unsupported` until a GLB articulation driver
   * exists — it is never silently ignored.
   */
  articulation?: GlbArticulationSpec;
  editableSurfaces: EditableSurface[];
  /** Camera framing for this product. */
  camera: {
    initial: [number, number, number];
    target: [number, number, number];
    minDistance: number;
    maxDistance: number;
    presets: CameraPreset[];
  };
  /** Vertical offset applied to the model so it sits on the ground plane. */
  modelYOffset?: number;
  /** Uniform scale applied without modifying the source GLB. */
  modelScale?: number;
  /** Ground-plane height when it differs from the model origin. */
  shadowY?: number;
  /** Hide from the library/catalogue while keeping the URL working. */
  hidden?: boolean;
  /** Optional key into the reusable print-profile registry. */
  printProfileId?: string;
  /** Product-specific production material response. */
  materialProfile?:
    | "standard"
    | "glossy-laminate"
    | "clear-barrier-gloss"
    | "kraft-corrugated"
    | "cotton-fabric";
};

/** Result of checking a loaded GLB against its ProductConfig. */
export type ValidationResult = {
  ok: boolean;
  errors: string[];
  foundMeshes: string[];
};
