import type { MaterialProfile } from "./types";

export const PACDORA_LAB_MATERIALS = [
  {
    id: "e-flute",
    label: "E-flute corrugated · 1.5 mm",
    kind: "corrugated",
    caliperMm: 1.5,
    color: "#d7bf93",
    roughness: 0.86,
    metalness: 0,
    transmission: 0,
    opacity: 1,
    clearcoat: 0,
    clearcoatRoughness: 1,
    scoreAllowanceFactor: 2 / 3,
    outerAllowanceFactor: 1 / 3,
    closureStackFactor: 5 / 3,
  },
  {
    id: "b-flute",
    label: "B-flute corrugated · 3 mm",
    kind: "corrugated",
    caliperMm: 3,
    color: "#c9aa76",
    roughness: 0.9,
    metalness: 0,
    transmission: 0,
    opacity: 1,
    clearcoat: 0,
    clearcoatRoughness: 1,
    scoreAllowanceFactor: 0.72,
    outerAllowanceFactor: 0.38,
    closureStackFactor: 1.55,
  },
  {
    id: "folding-board",
    label: "Folding boxboard · 0.45 mm",
    kind: "paperboard",
    caliperMm: 0.45,
    color: "#ffffff",
    roughness: 0.64,
    metalness: 0,
    transmission: 0,
    opacity: 1,
    clearcoat: 0.08,
    clearcoatRoughness: 0.72,
    scoreAllowanceFactor: 0.55,
    outerAllowanceFactor: 0.45,
    closureStackFactor: 1.25,
  },
  {
    id: "matte-film",
    label: "Matte plastic film · 0.12 mm",
    kind: "film",
    caliperMm: 0.12,
    color: "#ffffff",
    roughness: 0.52,
    metalness: 0,
    transmission: 0,
    opacity: 1,
    clearcoat: 0.12,
    clearcoatRoughness: 0.42,
    scoreAllowanceFactor: 0,
    outerAllowanceFactor: 0,
    closureStackFactor: 0,
  },
  {
    id: "glossy-film",
    label: "Glossy plastic film · 0.12 mm",
    kind: "film",
    caliperMm: 0.12,
    color: "#ffffff",
    roughness: 0.08,
    metalness: 0.03,
    transmission: 0,
    opacity: 1,
    clearcoat: 0.9,
    clearcoatRoughness: 0.1,
    scoreAllowanceFactor: 0,
    outerAllowanceFactor: 0,
    closureStackFactor: 0,
  },
  {
    id: "soft-touch-film",
    label: "Soft-touch plastic film · 0.13 mm",
    kind: "film",
    caliperMm: 0.13,
    color: "#ffffff",
    roughness: 0.78,
    metalness: 0,
    transmission: 0,
    opacity: 1,
    clearcoat: 0.02,
    clearcoatRoughness: 0.9,
    scoreAllowanceFactor: 0,
    outerAllowanceFactor: 0,
    closureStackFactor: 0,
  },
  {
    id: "clear-film",
    label: "Clear glossy film · 0.11 mm",
    kind: "film",
    caliperMm: 0.11,
    color: "#ffffff",
    roughness: 0.12,
    metalness: 0,
    transmission: 0.32,
    opacity: 0.88,
    clearcoat: 0.78,
    clearcoatRoughness: 0.14,
    scoreAllowanceFactor: 0,
    outerAllowanceFactor: 0,
    closureStackFactor: 0,
  },
  {
    id: "pearl-film",
    label: "Pearlescent laminate · 0.13 mm",
    kind: "film",
    caliperMm: 0.13,
    color: "#f7f6f2",
    roughness: 0.22,
    metalness: 0.16,
    transmission: 0,
    opacity: 1,
    clearcoat: 0.62,
    clearcoatRoughness: 0.2,
    scoreAllowanceFactor: 0,
    outerAllowanceFactor: 0,
    closureStackFactor: 0,
  },
  {
    id: "foil-film",
    label: "Aluminium laminate · 0.14 mm",
    kind: "film",
    caliperMm: 0.14,
    color: "#c8ccd2",
    roughness: 0.28,
    metalness: 0.62,
    transmission: 0,
    opacity: 1,
    clearcoat: 0.48,
    clearcoatRoughness: 0.24,
    scoreAllowanceFactor: 0,
    outerAllowanceFactor: 0,
    closureStackFactor: 0,
  },
] as const satisfies readonly MaterialProfile[];

export function getPacdoraLabMaterial(
  id: string,
  expectedKind?: "rigid" | "film",
): MaterialProfile {
  const material = PACDORA_LAB_MATERIALS.find((candidate) => candidate.id === id);
  if (!material) throw new Error(`Unknown Pacdora lab material: ${id}`);
  if (expectedKind === "rigid" && material.kind === "film") {
    throw new Error(`${material.label} cannot drive a carton construction.`);
  }
  if (expectedKind === "film" && material.kind !== "film") {
    throw new Error(`${material.label} cannot drive a flexible pouch construction.`);
  }
  return material;
}

export const PACDORA_LAB_BOX_MATERIALS = PACDORA_LAB_MATERIALS.filter(
  (material) => material.kind !== "film",
);

export const PACDORA_LAB_POUCH_MATERIALS = PACDORA_LAB_MATERIALS.filter(
  (material) => material.kind === "film",
);
